#!/bin/bash
set -e

echo "Starting tests at"
date "+%H:%M:%S"

export RACK_ENV="test"
export RACK_ROOT=$(cd "$(dirname $0)"/.. && pwd)

script/bootstrap
bundle exec rake test

echo "Attempting to build the gem..."
gem build geojson-diff.gemspec

echo "Done!"
